
spring:
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com/sql12660604
    username: sql12660604
    password: QSLjKshlzJ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
